services:
  backend_cuipo:
    image: cuipo-backend:1.0
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env  # Asegúrate de que el archivo .env esté en el mismo directorio
    ports:
      - "3056:3056"
    networks:
      - cuipo-net
 
networks:
  cuipo-net:
    driver: bridge