version: '3.8'
services:
  backend_cuipo:
    image: cuipo-backend:1.0
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8001:8001"  # Aquí expone el puerto 3056 del contenedor en el puerto 80 del host (ajustado al puerto adecuado)
    networks:
      - cuipo-net

networks:
  cuipo-net:
    driver: bridge
