server:
  port: ${SERVER_PORT:8001}  
  address: ${SERVER_ADDRESS:0.0.0.0}  


spring:
  application:
    name: baseapp
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev} 
  datasource:
    username: ${DATASOURCE_USERNAME:USR_DB_CUIPO} 
    password: ${DATASOURCE_PASSWORD:123}  
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: ${DATASOURCE_URL:jdbc:sqlserver://192.168.27.99:1433;databaseName=DB_CUIPO;encrypt=true;trustServerCertificate=true;loginTimeout=3600;queryTimeout=7200} 
    hikari:
      connection-timeout: 3600000
      max-lifetime: 7200000
      idle-timeout: 1200000
      maximum-pool-size: 30
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    show-sql: false
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
          fetch_size: 5000
        order_inserts: true
        order_updates: true
        format_sql: false

  output:
    ansi:
      enabled: always


security:
  enable: false
  user:
    name: ${SECURITY_USERNAME:user}  
    password: ${SECURITY_PASSWORD:Colombia2024*}  

jwt:
  secret:
    key: ${JWT_SECRET_KEY:U6w3yjuQRNWNRG3IaajKZY8nyMPiu+wFLpj/7evdNEc=} 

logging:
  level:
    "[org.hibernate.SQL]": debug

external:
  auth:
    url: ${external.auth.ur:https://serviciosint.contraloria.gov.co/directorio/usuarios/autenticar}


TABLA_PROG_INGRESOS: ${TABLA_PROG_INGRESOS:VW_OPENDATA_A_PROGRAMACION_INGRESOS} 
TABLA_EJEC_INGRESOS: ${TABLA_EJEC_INGRESOS:VW_OPENDATA_B_EJECUCION_INGRESOS} 
TABLA_PROG_GASTOS: ${TABLA_PROG_GASTOS:VW_OPENDATA_C_PROGRAMACION_GASTOS} 
TABLA_EJEC_GASTOS: ${TABLA_EJEC_GASTOS:VW_OPENDATA_D_EJECUCION_GASTOS}  
