# Configuración del servidor
server:
  port: ${SERVER_PORT}
  address: ${SERVER_ADDRESS}

# Configuración de la aplicación
spring:
  application:
    name: baseapp
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  datasource:
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: ${DATASOURCE_URL}
    hikari:
      connection-timeout: 3600000
      max-lifetime: 7200000
      idle-timeout: 1200000
      maximum-pool-size: 30
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    show-sql: false
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
          fetch_size: 5000
        order_inserts: true
        order_updates: true
        format_sql: false

  output:
    ansi:
      enabled: always
  
# Configuración Seguridad de la aplicación
security:
  enable: false
  user:
    name: ${SECURITY_USERNAME}
    password: ${SECURITY_PASSWORD}

# Clave secreta para JWT
jwt:
  secret:
    key: ${JWT_SECRET_KEY}

# Configuración del logging
logging:
  level:
    "[org.hibernate.SQL]": debug

external:
  auth:
    url: ${external.auth.ur:https://serviciosint.contraloria.gov.co/directorio/usuarios/autenticar}
    # Configuración auth cgr o ldap
    mode: cgr
    #mode: ldap
